# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuari', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='infocompos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=50)),
                ('genere', models.CharField(max_length=50, unique=True)),
                ('bpms', models.IntegerField()),
                ('tonalitat', models.CharField(max_length=50)),
                ('definicio', models.CharField(blank=True, max_length=300)),
                ('imatge_compo', models.ImageField(blank=True, default='../../static/Compo/DefaultCompo.png', upload_to='../../static/Compo')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuari.usuari')),
            ],
        ),
    ]
