# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compo', '0005_auto_20190524_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocompos',
            name='titol',
            field=models.CharField(default='Compo', max_length=100),
        ),
        migrations.AlterField(
            model_name='infocompos',
            name='imatge_compo',
            field=models.ImageField(blank=True, default='../static/Compo/DefaultCompo.png', upload_to='ImatgesCompos'),
        ),
    ]
