# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 14:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='usuari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correu', models.CharField(max_length=50, unique=True)),
                ('imatge_perfil', models.ImageField(blank=True, default='../../static/Usuari/DefaultPerfil.png', upload_to='../../static/Usuari')),
                ('usuaris', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
