# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuari', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuari',
            name='imatge_perfil',
            field=models.ImageField(blank=True, default='/static/Usuari/DefaultPerfil.png', upload_to='ImatgesPerfil/avatar'),
        ),
    ]
